function addWindowOnLoadEvent(fn){let oldOnLoad;if(typeof fn!=='function'){throw'Parameter "fn" must be a function: '+typeof fn;}
if(typeof window.onload==='function'){oldOnLoad=window.onload;window.onload=function(){if(oldOnLoad){oldOnLoad();}
fn();};}else{window.onload=fn;}}
function jsonp(url,callback){let callbackName='jp_'+Math.round(100000*Math.random()),d=document,script;window[callbackName]=function(data){delete window[callbackName];d.body.removeChild(script);callback(data);};script=d.createElement('script');script.src=url+(url.indexOf('?')>=0?'&':'?')+'c='+callbackName;d.body.appendChild(script);}
function setIntervalRedirect(countDown,redirectUri,className,redirectText){if(typeof countDown!=='number'){throw'timeOut is not a number';}
if(redirectUri===undefined){throw'redirectUri is undefined';}
let d=document,w=window,parentElement=d.querySelector(className)?d.querySelector(className):d.body,overlayDiv=d.createElement('div'),textDiv=d.createElement('div'),countDownFn;overlayDiv.className='nfyf-community-user-kicked-overlay';textDiv.className='nfyf-community-user-kicked-info';overlayDiv.appendChild(textDiv);parentElement.appendChild(overlayDiv);countDownFn=function(){if(countDown>=0){if(textDiv!==null){if(textDiv.innerText===undefined){textDiv.textContent=redirectText.replace('{countDown}',countDown.toString());}else{textDiv.innerText=redirectText.replace('{countDown}',countDown.toString());}}
countDown--;if(countDown===0){w.location.href=redirectUri;}}};countDownFn();w.setInterval(countDownFn,1000);}
function openLinkWindow(link,width,height,left,top,scrollbars,resizable,status){let linkPopUp=window.open(link,'LinkPopUp','toolbar=no,scrollbars='+scrollbars+',status='+status+',menubar=no,location=no,resizable='+resizable+',width='+width+',height='+height+',left='+left+',top='+top);if(linkPopUp.opener===null){linkPopUp.opener=self;}
linkPopUp.focus();}
function getLayer(attr){return(document.getElementById(attr)||document.getElementsByName(attr)[0]||null);}
function showHideAdLayer(){let v,i,obj,args=arguments;for(i=0;i<args.length-2;i+=3){if((obj=getLayer(args[i]))!==null&&obj.style!==undefined){v=args[i+2];obj.style.display=(v==='block'?'block':(v==='none'?'none':v));}}}
function getItemStatisticResource(shortcode,datasetId,puId,type){return'/REST/frontend/itemstatistics/'+shortcode+'/'+datasetId+'?puid='+(puId||'')+'&amp;type='+(type||0)+'&amp;rand='+(Math.random()*100000);}
function getItemStatisticImage(shortcode,datasetId,puId,type){return'<img src="'+getItemStatisticResource(shortcode,datasetId,puId,type)+'" width="1" height="1" />';}
function item_statistic(shortcode,datasetId,puId,type){document.write(getItemStatisticImage(shortcode,datasetId,puId,type));}
function getUnobscuredLink(string){let charNumber=0,link='',i;for(i=0;i<string.length;i++){charNumber=string.charCodeAt(i);if(charNumber>=8364){charNumber=128;}
link+=String.fromCharCode(charNumber-(1));}
return link;}
function unobscure(link){location.href=getUnobscuredLink(link);}
function onClickSetCachingHashCookie(element,value){element.addEventListener('click',function(){document.cookie='rf_vcc='+value;location.reload();});}
function autoHeightIframe(obj){let IframeHeight=obj.contentWindow.document.body.scrollHeight;if(IframeHeight==0){obj.style.display='none';obj.style.height='0px';obj.style.margin='0px';obj.style.padding='0px';obj.setAttribute('height','0px');}else{obj.style.height=parseInt(IframeHeight+20)+'px';obj.setAttribute('height',parseInt(IframeHeight+20));}}
function nfyStroeerSlot(adSlot,isCustom,customParam){if(window.nfy_stroeer_script_loaded===false){window.nfy_stroeer_script.addEventListener('load',function(){nfyStroeerLoadSlot(adSlot,isCustom,customParam);});}else{nfyStroeerLoadSlot(adSlot,isCustom,customParam);}}
function nfyStroeerLoadSlot(adSlot,isCustom,customParam){if(typeof SDG!=='undefined'){try{let position=adSlot,container='stroeer-container-'+adSlot;if(Boolean(isCustom)){let param=JSON.parse(customParam),width=typeof param['width']!=='undefined'?param['width']:0,height=typeof param['height']!=='undefined'?param['height']:0,adServerSizes=typeof param['dimension']!=='undefined'?param['dimension']:[],isMobile=typeof param['mobile']!=='undefined'?param['mobile']:false,useSubzone=typeof param['subzone']!=='undefined'?param['subzone']:'';if(useSubzone!==''){SDG.Publisher.registerModularSlot(position,container,width,height,adServerSizes,isMobile,useSubzone).load();}else{SDG.Publisher.registerModularSlot(position,container,width,height,adServerSizes,isMobile).load();}}else{SDG.Publisher.registerSlot(position,container).load();}}catch(err){console.log(err);}}}
function nfySerialize(data){let byShortCode={},implodedIdsByShortCode=[];data.forEach(function(v){let splitted=v.split('#');if(!byShortCode[splitted[1]]){byShortCode[splitted[1]]=[];}
byShortCode[splitted[1]].push(splitted[0]);});for(let k in byShortCode){implodedIdsByShortCode.push(k+'='+byShortCode[k].join('|'));}
return encodeURIComponent(implodedIdsByShortCode.join('#'));}
function nfyUnserialize(data){let tmp=decodeURIComponent(data),unserializedData=[];tmp=tmp.split('#');tmp.forEach(function(v){let splittedCodeAndIds=v.split('='),splitted=splittedCodeAndIds[1].split('|');splitted.forEach(function(data){unserializedData.push(data+'#'+splittedCodeAndIds[0]);});});return unserializedData;}var NFYAdvertisement=function(){var _api={};_api.showHideLayerAdvert=function(){var i,p,v,img,obj;for(i=0;i<(arguments.length-2);i+=3){if((obj=findObj(arguments[i]))!=null){img=findObj('img_'+arguments[i]);v=arguments[i+2];if(obj.style){obj=obj.style;v=(v=='block')?'block':(v=='hide')?'none':v;}
obj.display=v;obj.width=img.width+'px';obj.height=img.height+20+'px';}}};var findObj=function(n,d){var p,i,x;if(!d)d=document;if((p=n.indexOf("?"))>0&&parent.frames.length){d=parent.frames[n.substring(p+1)].document;n=n.substring(0,p);}
if(!(x=d[n])&&d.all)x=d.all[n];for(i=0;!x&&i<d.forms.length;i++)x=d.forms[i][n];for(i=0;!x&&d.layers&&i<d.layers.length;i++)x=findObj(n,d.layers[i].document);if(!x&&document.getElementById)x=document.getElementById(n);return x;};_api.showFlashBanner=function(cfg){if(!cfg||!swfobject)return;if(swfobject.hasFlashPlayerVersion(cfg.requiredFlashVersion)){var fn=function(){var attributes={data:cfg.path+cfg.filename,width:cfg.width,height:cfg.height},params={flashvars:"target="+cfg.target+"&clickTAG="+cfg.link.replace(/&amp;/g,"%26"),quality:"high",wmode:"transparent",allowscriptaccess:"always",menu:false,bgcolor:"#FFFFFF"};var nfySwf=swfobject.createSWF(attributes,params,cfg.id);}
swfobject.addDomLoadEvent(fn);}else{if(cfg.alt_file!=''){document.getElementById(cfg.id).innerHTML='<a href="'+cfg.link+'"><img src="'+cfg.path+cfg.alt_file+'" alt="" border="0" /></a>';}}};_api.hideUnpublishedOMSAd=function(selector){var img=$(selector).find('img');if(img){for(i=0;i<img.length;i++){if((img[i].src).match(/817-grey.gif/g)){$(selector).hide();return true;break;}}}
return false;};return _api;}();var NFYF_GoogleMapsV3=function(args){var attr,_api={gmap:null,centerLat:null,centerLng:null,sensor:false,legendOptions:{},circleOptions:null,circle:null,markerObjects:[],marker:{},legend:{},icons:{},userIcon:null,initialize:function(idSuffix,gmapOptions){var me=this,group;me.gmap=new google.maps.Map(document.getElementById('map_canvas'+idSuffix),gmapOptions);if(me.marker&&me.icons){me.setMarkerImages();}
if(me.showGroup){if(typeof me.group==='object'){for(group in me.group){me.showGroup(me.group[group]);}}else{me.showGroup(me.group);}}
if(me.sensor){me.trackPosition();}
if(me.circleOptions.show){me.drawCircle();}
if(me.legendOptions.show){me.showLegendControl();}},createMarker:function(latlng,message,icon,isDraggable){var me=this,infowindow,marker=new google.maps.Marker({position:latlng,map:me.gmap,icon:icon,draggable:!!isDraggable});if(message){infowindow=new google.maps.InfoWindow({content:message});google.maps.event.addListener(marker,'click',function(){infowindow.open(me.gmap,marker);});}
return marker;},createMarkerImage:function(icon){return{url:icon.iconUrl,size:(icon.iconSize)?new google.maps.Size(icon.iconSize):null,origin:(icon.origin)?new google.maps.Point(icon.origin):null,anchor:(icon.anchor)?new google.maps.Point(icon.anchor):null,scaledSize:(icon.scaledSize)?new google.maps.Size(icon.scaledSize):null};},setMarkerImages:function(){var me=this,i,group,markerImage;for(group in me.marker){if(me.icons[group]){markerImage=me.createMarkerImage(me.icons[group]);for(i in this.marker[group]){me.marker[group][i].icon=markerImage;}}}},showGroup:function(group,distance){var me=this,i,latlng,center=new google.maps.LatLng(me.centerLat,me.centerLng);for(i in me.marker[group]){latlng=new google.maps.LatLng(me.marker[group][i].lat,me.marker[group][i].lng);if(!distance||me.distanceBetweenPoints(center,latlng)<(distance/1000)){if(!me.markerObjects[group]){me.markerObjects[group]=[];}
me.markerObjects[group].push(me.createMarker(latlng,me.marker[group][i].html,me.marker[group][i].icon));}}},hideGroup:function(group){var me=this,i;if(me.markerObjects[group]){for(i in me.markerObjects[group]){if(me.markerObjects[group][i]){me.markerObjects[group][i].setMap(null);delete me.markerObjects[group][i];}
if(me.markerObjects[group]&&me.markerObjects[group].length===0){delete me.markerObjects[group];}}}},distanceBetweenPoints:function(p1,p2){if(!p1||!p2){return 0;}
var dLat,dLon,a,c,d,R=6371;dLat=(p2.lat()-p1.lat())*Math.PI/180;dLon=(p2.lng()-p1.lng())*Math.PI/180;a=Math.sin(dLat/2)*Math.sin(dLat/2)+Math.cos(p1.lat()*Math.PI/180)*Math.cos(p2.lat()*Math.PI/180)*Math.sin(dLon/2)*Math.sin(dLon/2);c=2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));d=R*c;return d;},drawCircle:function(){var me=this;if(me.circleOptions){if(!me.circleOptions.latitude&&!me.circleOptions.longitude){me.circleOptions.latitude=me.centerLat;me.circleOptions.longitude=me.centerLng;}
me.circle=new google.maps.Circle({map:this.gmap,radius:me.circleOptions.radius,center:new google.maps.LatLng(me.circleOptions.latitude,me.circleOptions.longitude),strokeColor:me.circleOptions.strokeColor,strokeWeight:me.circleOptions.strokeWeight,fillColor:me.circleOptions.fillColor});}},showLegendControl:function(){var me=this,displayButton=me.createElement('div',{id:'displaybutton',innerHTML:'Ausblenden'}),legendContainer=me.createElement('div',{id:'legendcontainer',className:'googlemaps'}),dockContainer=me.createElement('div'),group,checkbox,groupContainer,image,groupName;google.maps.event.addDomListener(displayButton,'click',me.bind(me.toggleLegend,me));if(me.legend){for(group in me.legend){groupContainer=me.createElement('div',{className:'groupcontainer'});if(me.legend[group].legendIconUrl){image=me.createElement('img',{className:'legendimage',src:me.legend[group].legendIconUrl});}else{image=me.createElement('img',{className:'legendimage',src:me.icons[group].iconUrl});}
checkbox=me.createElement('input',{className:'checkbox',type:'checkbox'});if(this.markerObjects[group]){checkbox.checked=true;}
google.maps.event.addDomListener(checkbox,'click',me.bind(me.toggleGroup,me,[checkbox,group]));groupName=me.createElement('div',{className:'name',innerHTML:this.legend[group].legendName});groupContainer.appendChild(image);groupContainer.appendChild(groupName);groupContainer.appendChild(checkbox);legendContainer.appendChild(groupContainer);}}
if(me.legendOptions.showCircumSearch){legendContainer.appendChild(me.showCircumControl());}
legendContainer.appendChild(displayButton);dockContainer.appendChild(legendContainer);me.gmap.controls[google.maps.ControlPosition[me.legendOptions.position]].push(dockContainer);},toggleGroup:function(cb,group){var me=this;if(cb.checked===true){me.showGroup(group);}else{me.hideGroup(group);}},toggleLegend:function(){var me=this,cHeight,displayButton=document.getElementById('displaybutton');if(displayButton){cHeight=me.getStylePropertyValue('legendcontainer','height');if(displayButton.innerHTML==='Ausblenden'){if($){$('#legendcontainer').animate({top:'-='+cHeight},250,function(){});}else{document.getElementById('legendcontainer').style.top=-cHeight;}
displayButton.innerHTML='Einblenden';}else{if($){$('#legendcontainer').animate({top:'0px'},250,function(){});}else{document.getElementById('legendcontainer').style.top='0px';}
displayButton.innerHTML='Ausblenden';}}},getStylePropertyValue:function(id,property){var element=document.getElementById(id),style=window.getComputedStyle(element);return style.getPropertyValue(property);},showCircumControl:function(){var me=this,distance,circumName=me.createElement('div',{className:'circumsearchName',innerHTML:'Suche in Umkreis'}),circumsearchDiv=me.createElement('div',{className:'circumsearch'}),select=me.createElement('select',{className:'selection'}),options,selectOptions=me.legendOptions.circumOptions;for(distance in selectOptions){options=me.createElement('option',{value:distance,innerHTML:selectOptions[distance]});select.appendChild(options);}
select.addEventListener('change',me.bind(me.toggleDistance,me,[select]));circumsearchDiv.appendChild(circumName);circumsearchDiv.appendChild(select);return circumsearchDiv;},toggleDistance:function(select){var me=this,group,distance=parseInt(select.value,10);if(me.circle){me.circle.setRadius(distance);}
if(me.markerObjects){for(group in me.markerObjects){if(me.markerObjects[group]){me.hideGroup(group);me.showGroup(group,distance);}}}
me.gmap.setCenter(new google.maps.LatLng(me.centerLat,me.centerLng));switch(distance){case 0:return me.gmap.setZoom(10);case 500:return me.gmap.setZoom(15);case 1000:return me.gmap.setZoom(14);case 2000:return me.gmap.setZoom(13);case 5000:return me.gmap.setZoom(11);default:return me.gmap.setZoom(10);}},createElement:function(type,args){var attr,element=document.createElement(type);for(attr in args){element[attr]=args[attr];}
return element;},bind:function(fn,scope,args){return function(){return fn.apply(scope,args);};},trackPosition:function(){if(!navigator.geolocation){console.warn('HTML5 Geolocation API is not supported by this browser.');return;}
if(this.userIcon.length===0){console.error('No user icon path set in Google Maps V3 class.');return;}
var me=this,geolocationID,count,markerUser=me.createMarker(null,null,me.createMarkerImage(me.userIcon));if((navigator.userAgent.match(/iPhone/i))||(navigator.userAgent.match(/iPod/i))){me.setUserPosition(me.getPosition(),markerUser);(function locationTimer(){count=0;geolocationID=window.setInterval(function(){count++;if(count>3){window.clearInterval(geolocationID);locationTimer();}else{me.setUserPosition(me.getPosition(),markerUser);}},10000);})();}else{navigator.geolocation.getCurrentPosition(function(position){me.setUserPosition(position,markerUser);},function(){alert('An error occured while retreiving the position.');});}},getPosition:function(){navigator.geolocation.getCurrentPosition(function(position){return position;},function(){console.log('An error occured while retreiving the position.');},{enableHighAccuracy:true,timeout:10000});},setUserPosition:function(position,markerUser){var me=this,initialLocation;me.centerLat=position.coords.latitude;me.centerLng=position.coords.longitude;initialLocation=new google.maps.LatLng(me.centerLat,me.centerLng);if(initialLocation&&me.gmap){google.maps.event.addListenerOnce(me.gmap,'idle',function(){me.gmap.setCenter(initialLocation);});markerUser.setPosition(initialLocation);if(me.circle){me.circle.setCenter(initialLocation);me.circle.bindTo('center',markerUser,'position');}}}};for(attr in args){_api[attr]=args[attr];}
return _api;};;function SetCookie(name,value){var argv=SetCookie.arguments;var argc=SetCookie.arguments.length;var expires=(argc>2)?argv[2]:null;var path=(argc>3)?argv[3]:null;var domain=(argc>4)?argv[4]:null;var secure=(argc>5)?argv[5]:false;document.cookie=name+"="+escape(value)+
((expires==null)?"":("; expires="+expires.toGMTString()))+
((path==null)?"":("; path="+path))+
((domain==null)?"":("; domain="+domain))+
((secure==true)?"; secure":"");}
function GetCookie(name)
{var a_all_cookies=document.cookie.split(';');var a_temp_cookie='';var cookie_name='';var cookie_value='';var b_cookie_found=false;for(i=0;i<a_all_cookies.length;i++){a_temp_cookie=a_all_cookies[i].split('=');cookie_name=a_temp_cookie[0].replace(/^\s+|\s+$/g,'');if(cookie_name==name){b_cookie_found=true;if(a_temp_cookie.length>1){cookie_value=unescape(a_temp_cookie[1].replace(/^\s+|\s+$/g,''));}
return cookie_value;break;}
a_temp_cookie=null;cookie_name='';}
if(!b_cookie_found){return null;}}
function nfyc_item_statistic(shortCode,dsId,puId,type)
{if(!puId){puId=1;}
if(!type){type=0;}
html='<img src="/REST/frontend/itemstatistics/'+shortCode+'/'+dsId+'?puid='+puId+'&amp;type='+type+'&amp;rand='+(Math.random()*100000)+'" width="1" height="1" />';jQuery('body').append(html);}
function resizeIframe(obj)
{var IframeHeight=obj.contentWindow.document.body.scrollHeight;if(IframeHeight==0)
{obj.style.display="none";obj.style.height="0px";obj.style.margin="0px";obj.style.padding="0px";obj.setAttribute('height','0px');}
else{obj.style.height=parseInt(IframeHeight+20)+"px";obj.setAttribute('height',parseInt(IframeHeight+20));}}
function scaleAd(iframe)
{iframe.style.width="100%";iframe.find("img").css("width","100%");iframe.find("img").css("height","auto");}
function uploadFilePath(obj)
{var name=obj.value;if(window.File)
{name=obj.files[0].name;}
jQuery(obj).next().val(name);}